# Generated by Django 4.0.2 on 2022-02-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date_created',
        ),
    ]
