# Generated by Django 4.0.2 on 2022-02-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[('1', 'Easy'), ('2', 'Hard'), ('3', 'Medium')], null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='app.quiz'),
        ),
    ]
