# Generated by Django 4.0.2 on 2022-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_question_category_question_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[('1', 'Easy'), ('2', 'Hard'), ('3', 'Medium')], default=0, null=True, verbose_name='Difficulty Level'),
        ),
    ]
