# Generated by Django 4.0.2 on 2022-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_question_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[('Easy', '1'), ('Hard', '2'), ('Medium', '3')], default=0, null=True, verbose_name='Difficulty Level'),
        ),
    ]
